test_add_two_negative (class_0405_unittest.class_01.TestMathMethod) ... ok
test_add_two_positive (class_0405_unittest.class_01.TestMathMethod) ... ok
test_add_two_zero (class_0405_unittest.class_01.TestMathMethod) ... FAIL

======================================================================
FAIL: test_add_two_zero (class_0405_unittest.class_01.TestMathMethod)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\11\Desktop\ningmeng\class_0405_unittest\class_01.py", line 31, in test_add_two_zero
    self.assertEqual(1, res,'两个0相加出错了')
AssertionError: 1 != 0 : 两个0相加出错了

----------------------------------------------------------------------
Ran 3 tests in 0.001s

FAILED (failures=1)
